version: '3.9'

services:
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./gitlab/config:/etc/gitlab
      - ./gitlab/logs:/var/log/gitlab
      - ./gitlab/data:/var/opt/gitlab


  nginx:
    image: 'nginx:latest'
    ports:
      - "8080:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/html:/usr/share/nginx/html

networks:
  default:
    driver: bridge